### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by maaaaz** [ropnop/blog.ropnop.com#7]
Hey pal,
Just to inform you that unfortunately image links are broken here https://blog.ropnop.com/using-credentials-to-own-windows-boxes-part-2-psexec-and-services/

Cheers.
Thomas.

**Comment by ropnop** [comment]
Hey thanks so much for letting me know, I had no idea! Simple fix, should be good now. Thanks again 👍

**Comment by maaaaz** [comment]
Thanks ! 
I quickly checked all other blog posts and only this one had obvious broken stuff.
